project:
  type: website
  output-dir: docs
website:
  title: "books.lostineconomics.com"
  site-url: https://books.lostineconomics.com
  favicon: "favicon.ico"
  navbar:
    right:
      - text: "Blog"
        href: https://blog.lostineconomics.com
      - about.qmd
      - icon: github
        href: https://github.com/anarinsk
      #- icon: twitter
      #  href: https://twitter.com
  #body-header: google_analytics.html
format:
  html:
    include-before-body: "google_analytics.html"
    theme: [cosmo, anari-custom.scss] 
      #dark: [vapor, theme-dark.scss, anari-custom.scss]  
      #light: [vapor, theme.scss, anari-custom.scss]
  #css: styles.css



